routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Auth::routes();

// Routes for Products
Route::get('/', 'ProductController@index');
Route::resource('products', 'ProductController');

//Routes for Users
Route::get('/home', 'HomeController@index');
Route::get('account', 'AccountSettingsController@index');
Route::post('account', 'AccountSettingsController@updateAccount');

//Routes for Wishlist
Route::post('wishlist/{product}',['as' => 'wishlist.update', 'uses' => 'WishlistController@update']);
Route::get('wishlist', 'WishlistController@index');
Route::post('wishlist/delete/{id}', ['as' => 'wishlist.destroy', 'uses' => 'WishlistController@destroy']);

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'price',
        'description',
        'urlImage',
        'category'
    ];

    public function getPriceOutputAttribute()
    {
        return '€'. number_format($this->price, 2);
    }

    public function scopeSearch($query, $name)
    {
        return $query->where('name', 'LIKE', "%$name%");
    }

    public function wishlists()
    {
        return $this->belongsToMany(Wishlist::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->get('filter') == 'low') {
            $products = Product::Search($request->name)->orderBy('price', 'asc')->get();
        }
        else{
            $products = Product::Search($request->name)->orderBy('price', 'desc')->get();
        }
        $products->each(function ($products) {
            $products->name;
            $products->description;
            $products->price;
            $products->urlImage;
            $products->category;
        });

        $user = Auth::id();
        $user_id = User::find($user);
        if(isset($user)){
            $wishes = $user_id->wishlist->products()->get();
            if(count($products) == 0){
                return view('products.index')->with(['products' => $products, 'selected' => $request->get('filter'), 'message' => 'Sorry, no data found', 'wishes' => $wishes ]);
            }
            else {
                return view('products.index')->with(['products' => $products, 'selected' => $request->get('filter'), 'wishes' => $wishes]);
            }
        }
        else{
            if(count($products) == 0){
                return view('products.index')->with(['products' => $products, 'selected' => $request->get('filter'), 'message' => 'Sorry, no data found' ]);
            }
            else {
                return view('products.index')->with(['products' => $products, 'selected' => $request->get('filter')]);
            }
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'price' => 'required|numeric',
            'description' => 'required',
            'urlImage' => 'nullable'
        ]);

        $product = new Product($request->all());

        //  To put in production I was use this name to save photos and no repeat names (For example)
        //  $imageName = time().'-'.$image->getClientOriginalName();
        if ($request->hasFile('urlImage')) {
            $image = $request->file('urlImage');
            $imageName = $image->getClientOriginalName();
            $image->move(public_path('img'), $imageName);
            $product->urlImage = $imageName;
        }
        $product->save();

        return view('products.index')->with('products', Product::all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $product = Product::find($id);
        return view('products.show')->with('product', $product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    private function redirectToProduct($product)
    {
        return redirect(route('product.show', $product->id));
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-default">
                    <div class="panel-heading">Add a Product</div>
                    <div class="panel-body">
                        <form class="form-horizontal" role="form" method="post" enctype="multipart/form-data"
                              action="{{ route('products.store') }}">
                            {{ csrf_field() }}
                            <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Name</label>
                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" placeholder="Name">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                                <label for="description" class="col-md-4 control-label">Description</label>
                                <div class="col-md-6">
                                    <textarea id="description" type="text" class="form-control" name="description"
                                              placeholder="Description"></textarea>
                                    @if ($errors->has('description'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group{{ $errors->has('price') ? ' has-error' : '' }}">
                                <label for="name" class="col-md-4 control-label">Price</label>
                                <div class="col-md-6">
                                    <input id="price" type="text" class="form-control" name="price" placeholder="Price">
                                    @if ($errors->has('price'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('price') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="form-group{{ $errors->has('category') ? ' has-error' : '' }}">
                                <label for="category" class="col-md-4 control-label">Category</label>
                                <div class="col-md-6">
                                    {{ Form::select('Category', [
                                       'Laundry Appliances' => 'Laundry Appliances',
                                       'Dishwashers' => 'Dishwashers',
                                       'Fridges & Freezers' => 'Fridges & Freezers',
                                       'Microwaves' => 'Microwaves',
                                       'Cooking' => 'Cooking',
                                       'Small Appliances' => 'Small Appliances']
                                    ,null, ['class' => 'form-control'])}}
                                    @if ($errors->has('category'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('category') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            
                            <div class="form-group{{ $errors->has('urlImage') ? ' has-error' : '' }}">
                                <label for="urlImage" class="col-md-4 control-label">Image</label>
                                <div class="col-md-6">
                                    <input id="urlImage" type="file" class="form-control" name="urlImage">
                                    @if ($errors->has('urlImage'))
                                        <span class="help-block">
                                        <strong>{{ $errors->first('urlImage') }}</strong>
                                    </span>
                                    @endif
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-6 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Add
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="jumbotron text-xs-center">
        <div class="container">
            <h1 class="jumbotron-heading">Welcome to Laravel</h1>
            <p class="lead text-muted">Example activity to work</p>
        </div>
    </section>
    <div class="container">
        <div class="well well-sm">
            @include('layouts.partials.order')
            @include('layouts.partials.search')
        </div>
        @if(isset($message))
            <div class="alert alert-warning">
                {{$message}}
            </div>
        @else
            <div id="products" class="row list-group">
                <div class="clearfix visible-xs"></div>
                @foreach($products as $product)
                    <div class="item  col-lg-4 col-sm-6 col-md-4 col-xs-12 vcenter">
                        <div class="thumbnail">
                            <a href="{{url('products/'.$product->id)}}">
                                <img class="group list-group-image" src="img/{{$product->urlImage}}" alt=""/>
                            </a>
                            <div class="caption">
                                <h4 class="group inner list-group-item-heading"><a
                                            href="{{url('products/'.$product->id)}}">{{$product->name}}</a></h4>
                                <p class="group inner list-group-item-text">{{str_limit($product->description, 120)}}</p>
                                <div class="row">
                                    <p class="price-list">{{$product->priceOutput}}</p>
                                </div>
                                <div class="row">
                                    <div class="text-center col-xs-12 col-md-6">
                                        @if(isset($wishes))
                                            <?php $i = 0; ?>
                                            @foreach($wishes as $wish)
                                                @if($wish->id == $product->id)
                                                    <div class="form-group">
                                                        <div class="col-md-6 col-md-offset-4">
                                                            <button class="btn btn-warning disabled">
                                                                Added!
                                                            </button>
                                                        </div>
                                                    </div>
                                                    <?php $i++; ?>
                                                @endif
                                            @endforeach
                                            @if($i == 0)
                                                {!! Form::open(['route' => ['wishlist.update', $product->id],'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post']) !!}
                                                <div class="form-group">
                                                    <div class="col-md-6 col-md-offset-4">
                                                        <button type="submit" class="btn btn-primary">
                                                            Add wish list
                                                        </button>
                                                    </div>
                                                </div>
                                                {!! Form::close() !!}
                                            @endif
                                        @else
                                            {!! Form::open(['route' => ['wishlist.update', $product->id],'class' => 'form-horizontal', 'role' => 'form', 'method' => 'post']) !!}
                                            <div class="form-group">
                                                <div class="col-md-6 col-md-offset-4">
                                                    <button type="submit" class="btn btn-primary">
                                                        Add wish list
                                                    </button>
                                                </div>
                                            </div>
                                            {!! Form::close() !!}
                                        @endif

                                    </div>
                                    <div class="text-center col-xs-12 col-md-6">
                                        <a class="btn btn-success" href="#">Buy Now</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        @endif
    </div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="product-detail">
            <div class="container-fluid">
                <div class="wrapper row">
                    <div class="preview col-md-6">
                        <div class="preview-pic tab-content">
                            <div class="tab-pane active" id="pic-1"><img src="../img/{{$product->urlImage}}" /></div>
                        </div>
                    </div>
                    <div class="details col-md-6">
                        <h3 class="product-title">{{$product->name}}</h3>
                        <p class="product-description">{{$product->description}}</p>
                        <h4 class="price text-center">{{$product->priceOutput}}</h4>
                        <div class="action">
                            <a class="btn btn-default" href="#">Add wish list</a>
                            <a class="btn btn-success" href="#">Buy Now</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection